In [1]:
import pandas as pd
import numpy as np

In [4]:
M = pd.read_csv('MovieReviewsSheet.csv', index_col='Name')

In [5]:
M

,American Sniper,The Hunger Games: Mockingjay - Part 1,Guardians of the Galaxy,The Lego Movie,The Hobbit,Transformers,Malificent,Big Hero 6,Godzilla,Interstellar,How to Train your Dragon 2,Gone Girl,Divergent,The Fault in Our Stars,Unbroken,300: Rise of an Empire
Name,,,,,,,,,,,,,,,,
Mike,NaN,NaN,5,NaN,4,NaN,3,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,2
HJ SONG,NaN,2,3,4,4,5,NaN,4,4,5,5,NaN,NaN,NaN,5,5
Ryan Hansen,NaN,3,4,3,5,2,3,3,3,NaN,5,NaN,3,NaN,NaN,NaN
Olumuyiwa Durojaiye,NaN,NaN,NaN,NaN,NaN,5,NaN,5,2,NaN,3,NaN,NaN,NaN,NaN,2
Charlie,NaN,2,3,NaN,3,2,3,NaN,4,5,2,NaN,2,3,NaN,2
Sina Tuy,NaN,3,4,3,5,2,3,4,3,NaN,3,4,3,2,NaN,2
Pavithra Shetty,NaN,3,NaN,NaN,4,5,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN
Sara Collins,NaN,5,5,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN
Jonathan Doll,NaN,4,NaN,3,4,2,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
saikiran reddy,3,4,4,NaN,4,5,4,NaN,5,5,4,4,2,5,NaN,2
Aishwarya reddy,NaN,3,4,3,4,4,3,NaN,4,4,3,5,NaN,4,NaN,3
Brant Mullinix,NaN,4,4,4,5,3,NaN,NaN,NaN,5,3,3,NaN,NaN,NaN,4
Sai Sampath,NaN,3,4,3,4,4,3,NaN,4,4,3,5,NaN,4,NaN,3
Suyendra,NaN,3,4,3,5,2,3,3,3,NaN,5,NaN,3,4,2,5
Sai Yallapragada,5,2,2,3,NaN,3,NaN,NaN,1,5,NaN,NaN,2,NaN,NaN,4
Akhilesh,NaN,NaN,4,3,5,4,NaN,NaN,NaN,5,NaN,3,NaN,NaN,NaN,5
Sundar Prasad,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,4
Evan Piercy,4,NaN,NaN,4,NaN,4,NaN,NaN,NaN,5,NaN,2,NaN,NaN,NaN,2
Jessica Fong,NaN,3,3,NaN,NaN,3,NaN,NaN,NaN,5,NaN,NaN,5,NaN,NaN,NaN
Onsiri Tapsarn,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN
Anirudh Thota,NaN,3,4,3,3,4,NaN,NaN,3,4,3,NaN,NaN,NaN,NaN,4
Greg Werner,5,3,3,NaN,NaN,4,4,NaN,NaN,5,4,5,4,NaN,NaN,4
Violeta Lee Fay,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,5,NaN,3,NaN,NaN,NaN,NaN,2
Aditya Dharmasagar,5,NaN,NaN,4,5,4,4,NaN,4,5,5,5,4,4,NaN,5
Manideep Maddipatla,4,3,4,3,5,4,NaN,4,4,4,4,NaN,3,NaN,3,5
Maheshwar Reddy,4,3,4,NaN,5,4,NaN,4,NaN,5,NaN,5,NaN,NaN,NaN,4
siddanth sudarshan,5,3,3,NaN,2,NaN,NaN,NaN,NaN,4,NaN,4,NaN,NaN,NaN,5
anurag,4,NaN,NaN,NaN,3,NaN,NaN,NaN,5,NaN,3,NaN,3,NaN,NaN,5
Ahmed Muheebuddin,5,NaN,4,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
azam,4,NaN,3,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aswini kumar,4,4,5,NaN,NaN,NaN,NaN,5,3,5,4,NaN,NaN,NaN,NaN,4
M A Nissar,4,4,5,NaN,5,NaN,5,5,4,3,4,3,2,4,NaN,4
Yinka Adeyemo,4,NaN,4,NaN,4,NaN,NaN,4,NaN,NaN,4,NaN,NaN,NaN,NaN,4
Thomas Podlipni,5,3,5,4,4,1,NaN,NaN,NaN,NaN,4,NaN,3,NaN,NaN,4
Bradley Brubaker,NaN,1,5,5,5,4,NaN,NaN,4,NaN,4,NaN,3,NaN,NaN,2
Harish Kallianpur,5,3,NaN,NaN,5,4,4,NaN,4,5,4,NaN,3,NaN,NaN,3
J A Barnes,NaN,3,4,NaN,4,4,NaN,NaN,NaN,NaN,3,NaN,3,NaN,NaN,NaN
Jared Knowles,NaN,NaN,5,4,NaN,NaN,4,NaN,NaN,NaN,4,NaN,NaN,NaN,5,NaN
veerendra battula,3,NaN,2,1,NaN,2,3,NaN,2,NaN,1,3,2,NaN,NaN,5
Trudy Kline,3,5,5,3,3,4,NaN,NaN,2,NaN,NaN,2,4,NaN,NaN,1
Rajesh Kinkirla,4,5,4,3,4,5,3,4,4,5,2,3,4,3,5,5

In [6]:
def pearson(s1, s2):
    """Take two pd.Series objects and return a pearson correlation."""
    s1_c = s1 - s1.mean()
    s2_c = s2 - s2.mean()
    return np.sum(s1_c * s2_c) / np.sqrt(np.sum(s1_c ** 2) * np.sum(s2_c ** 2))

In [7]:
def get_recs(movie_name, M, num):

    import numpy as np
    reviews = []
    for title in M.columns:
        if title == movie_name:
            continue
        cor = pearson(M[movie_name], M[title])
        if np.isnan(cor):
            continue
        else:
            reviews.append((title, cor))
    
    reviews.sort(key=lambda tup: tup[1], reverse=True)
    return reviews[:num]

In [19]:
recs = get_recs('The Fault in Our Stars', M, 10)

In [20]:
recs[:1]

[('How to Train your Dragon 2', 0.3415297689636223)]

In [10]:
my_ratings = M.ix['veerendra battula'].dropna()
#the movie I've rated the highest
my_ratings.sort(ascending=False)
#the name of the movie I've rated the highest
fav_movie = my_ratings.index[0]

In [11]:
fav_movie

'300: Rise of an Empire'

In [12]:
recs = get_recs(fav_movie, M, 10)

In [13]:
recs[:10]

[('American Sniper', 0.24506209106411833),
 ('Gone Girl', 0.15326891390908526),
 ('How to Train your Dragon 2', 0.13076165892569172),
 ('The Fault in Our Stars', 0.080689141155557934),
 ('The Hobbit', 0.077358360302105494),
 ('Divergent', 0.065453820630958101),
 ('Malificent', 0.057134506052907097),
 ('Godzilla', 0.028512209644097654),
 ('The Hunger Games: Mockingjay - Part 1', 0.009170929585710275),
 ('Interstellar', -0.067814672843601001)]

In [14]:
not_rated = M.ix['veerendra battula']
not_rated.sort()
for i in range(0, not_rated.count(), 1):
    not_rated.drop(not_rated.index[0], inplace=True)

In [21]:
not_rated

The Hunger Games: Mockingjay - Part 1   NaN
The Hobbit                              NaN
Big Hero 6                              NaN
Interstellar                            NaN
The Fault in Our Stars                  NaN
Unbroken                                NaN
Name: veerendra battula, dtype: float64

In [25]:
print "Pearson Correlation coefficient of :"
a= []
for i in range(0, M.shape[0], 1): # for each row in M (range(0,41))
    cor=pearson(M.ix[38], M.ix[i])
    print "(" + M.index[38] + " , " + M.index[i] + ") :", cor
    a.append(cor)

Pearson Correlation coefficient of :
(veerendra battula , Mike) : -0.542967674712
(veerendra battula , HJ SONG) : 0.13306378257
(veerendra battula , Ryan Hansen) : -0.125417888267
(veerendra battula , Olumuyiwa Durojaiye) : -0.295857325078
(veerendra battula , Charlie) : -0.0698584858493
(veerendra battula , Sina Tuy) : -0.174013879564
(veerendra battula , Pavithra Shetty) : -0.231183364022
(veerendra battula , Sara Collins) : -0.185495558304
(veerendra battula , Jonathan Doll) : 0.176499500659
(veerendra battula , saikiran reddy) : -0.449670668677
(veerendra battula , Aishwarya reddy) : 0.017527682735
(veerendra battula , Brant Mullinix) : 0.148414011471
(veerendra battula , Sai Sampath) : 0.017527682735
(veerendra battula , Suyendra) : 0.230613369952
(veerendra battula , Sai Yallapragada) : 0.383374238117
(veerendra battula , Akhilesh) : 0.419696672406
(veerendra battula , Sundar Prasad) : -0.34780417182
(veerendra battula , Evan Piercy) : -0.559953915154
(veerendra battula , Jessica Fong) : 0.0207390338946
(veerendra battula , Onsiri Tapsarn) : nan
(veerendra battula , Anirudh Thota) : 0.461433794767
(veerendra battula , Greg Werner) : 0.182171092056
(veerendra battula , Violeta Lee Fay) : -0.491869376838
(veerendra battula , Aditya Dharmasagar) : 0.360704209681
(veerendra battula , Manideep Maddipatla) : 0.501743990888
(veerendra battula , Maheshwar Reddy) : -0.0100402416113
(veerendra battula , siddanth sudarshan) : 0.476308622942
(veerendra battula , anurag) : 0.538213444213
(veerendra battula , Ahmed Muheebuddin) : 0.120482899335
(veerendra battula , azam) : 0.0803219328902
(veerendra battula , Aswini kumar) : -0.0379485462949
(veerendra battula , M A Nissar) : 0.0359210604054
(veerendra battula , Yinka Adeyemo) : nan
(veerendra battula , Thomas Podlipni) : 0.125699951859
(veerendra battula , Bradley Brubaker) : -0.511165650822
(veerendra battula , Harish Kallianpur) : -0.185495558304
(veerendra battula , J A Barnes) : 0.11593472394
(veerendra battula , Jared Knowles) : 0.165912271157
(veerendra battula , veerendra battula) : 1.0
(veerendra battula , Trudy Kline) : -0.514801591146
(veerendra battula , Rajesh Kinkirla) : 0.410551194126

In [26]:
def pred_rate(x, a):
    """
    Takes two parameters 'x' and 'a'. 
    Where 'x' a list of rates given by classmates. 
    'a' is a array that has corresponding pearson correlation coefficientreturn (weights for the given rates).
    predicted rate is calculated as rate= (x[0]*a[0] + x[1]*a[1] +...+x[i]*a[i]) / (a[0]+a[1]+..+a[i]) 
    returns predicted rate 
    """
    j=0
    k=0
    for i in range(0, x.shape[0], 1): # for each row in x (range(0,23))
        if x.irow(i)>0 and a[i]>0: 
            j= j+(a[i]*x.irow(i))
            k= k+a[i]
        else:
            continue
    return j/k

In [27]:
print "My ratings for the movies that I have not seen using class review:"
for i in range(0, not_rated.shape[0], 1): # for each row in not_rated(range(0,12))  
    x=M[not_rated.index[i]]
    rate=pred_rate(x, a)
    print not_rated.index[i] +": ", rate.round(1)

My ratings for the movies that I have not seen using class review:
The Hunger Games: Mockingjay - Part 1:  3.2
The Hobbit:  3.9
Big Hero 6:  3.9
Interstellar:  4.6
The Fault in Our Stars:  3.6
Unbroken:  3.8